services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: todo_app:latest
    container_name: todo-app
    ports:
      - "${APP_PORT}:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USER_NAME: ${DB_USER_NAME}
      DB_PASSWORD: ${DB_USER_PASSWORD}
    restart: always
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql
    container_name: todo-app-db
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_USER_PASSWORD}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
      MYSQL_DATABASE: todo_app_v2
    restart: always
    volumes:
      - todo_app_db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
volumes:
  todo_app_db:
    external: true
